### ISSUE TITLE
El equipamiento debería ser un equipamiento ya exxistente 

### ISSUE THREAD

**Issue by ocorcho** [josuesalas25/cultura-ocio-agenda-eventos-actividades#1]
En 
https://github.com/josuesalas25/cultura-ocio-agenda-eventos-actividades/blob/f7c7aa4516bebfa32cd01746351a7bc21d3b9986/v1.1-rc/examples/output.nt#L25

Se crea un equipamiento con el número de evento. Esto no parece tener sentido.

**Comment by josuesalas25** [comment]
Ahora el equipamiento se crea con el nombre del equipamiento. 

Un ejemplo es:  

`<http://vocab.linkeddata.es/datosabiertos/recurso/cultura-ocio/agenda/Evento/1285153785025> <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/equipamiento/Equipamiento> <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/equipamiento-municipal/Equipamiento/Centro%20Cultural%20de%20la%20Villa%20%28Lumbrales%29>.`

**Comment by ocorcho** [comment]
Sería ideal que el equipamiento tuviera un id propio. ¿No lo tiene en ningún sitio? Usar el nombre en la URI es muy poco efectivo.
Además, será /equipamiento/ en lugar de /Equipamiento/ en la URI

Lo mismo con el evento (/evento en lugar de /Evento)

**Comment by josuesalas25** [comment]
Se ha cambiado la URI de equipamiento de /Equipamiento/ a /equipamiento/.

Respecto al equipamiento, no he encontrado en los csv ningun id propio que los identifique. Por lo tanto, no se me ocurre que alternativa poner al id, ya que es la mejor opcion.

Ahora el ejemplo queda como:
`<http://vocab.linkeddata.es/datosabiertos/recurso/cultura-ocio/agenda/evento/1285153785025> <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/equipamiento/Equipamiento> <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/equipamiento-municipal/equipamiento/Centro%20Cultural%20de%20la%20Villa%20%28Lumbrales%29>.`

**Comment by ocorcho** [comment]
Hay varias opciones:
1. Crear un nodo en blanco que tenga dentro como rdfs:label el nombre del equipamiento.
2. En lugar de nodo en blanco, crear la URI http://vocab.linkeddata.es/datosabiertos/recurso/cultura-ocio/agenda/evento/1285153785025/equipamiento, a la espera de que se pueda reconciliar en el futuro, y añadir que ese equipamiento tiene como rdfs:label el nombre del equipamiento, para facilitar la tarea en el futuro.
3. Reconciliar este dataset con el de equipamientos de la ciudad, donde se puede esperar que estén estos equipamientos si están presentes en el dataset de eventos. Esto permitiría empezar a conectar unos conjuntos de datos con otros. Es laborioso, pero podría ser muy interesante si lo consigues.

**Comment by josuesalas25** [comment]
Creo que ya ha sido modificado correctamente.

Ademas, he actualizado el resto de la ontologia y derivados añadiendo en la clase Equipamiento el dato **esequip:id**

**Comment by ocorcho** [comment]
Usa dct:identifier

**Comment by josuesalas25** [comment]
Ya se ha cambiado toda la ontologia pasando a dct:identifier
