### ISSUE TITLE
Actualizar README de ejemplos

### ISSUE THREAD

**Issue by ocorcho** [josuesalas25/cultura-ocio-agenda-eventos-actividades#10]
En https://raw.githubusercontent.com/josuesalas25/cultura-ocio-agenda-eventos-actividades/master/v1.1-rc/examples/readme.md

Se debería mejorar la descripción del README. Ver https://github.com/MMB99/urbanismo-infraestructuras-alumbrado-publico/tree/master/v1.0-rc/mapping/Madrid para tener un ejemplo más detallado.

**Comment by josuesalas25** [comment]
Se ha actualizado la descripción de los ejemplos.
