### ISSUE TITLE
Revisar todas las URIs en el RDF generado

### ISSUE THREAD

**Issue by ocorcho** [josuesalas25/cultura-ocio-agenda-eventos-actividades#11]
En https://github.com/josuesalas25/cultura-ocio-agenda-eventos-actividades/blob/25085449324570362602536538249989839f0092/v1.1-rc/examples/output.nt#L292

La propiedad debería tener /def/ en la URI, y no /recurso/

Revisa en todos los elementos que se generan, para que la generación se haga adecuadamente:
- /def para los elementos de la ontología
- /recurso para los datos
- /kos para los SKOS

**Comment by josuesalas25** [comment]
https://github.com/josuesalas25/cultura-ocio-agenda-eventos-actividades/blob/b1dfc6616ee9dfe4481740e3bccb87b35a2af546/v1.1-rc/examples/output.nt#L2372

Se han realizado las modificaciones pertintentes, creo que ya todos se generan de forma adecuada
