### ISSUE TITLE
Error en la generación de RDF

### ISSUE THREAD

**Issue by ocorcho** [josuesalas25/cultura-ocio-agenda-eventos-actividades#12]
Me sorprende este error si ha sido generado con morph-kgc. ¿Puedes revisarlo?Esta línea está mal:

https://github.com/josuesalas25/cultura-ocio-agenda-eventos-actividades/blob/25085449324570362602536538249989839f0092/v1.1-rc/examples/output.nt#L950

**Comment by josuesalas25** [comment]
Se ha editado el archivo CSV y ya no se producen esos fallos
