### ISSUE TITLE
Poner los datatypes en datos boolean

### ISSUE THREAD

**Issue by ocorcho** [josuesalas25/cultura-ocio-agenda-eventos-actividades#2]
En 
<http://vocab.linkeddata.es/datosabiertos/recurso/cultura-ocio/agenda/Evento/1285153785025> <http://schema.org/isAccesibleForFree> "false".

Se debe añadir que es xsd:boolean

**Comment by josuesalas25** [comment]
Se ha añadido el tipo de dato boolean a todos los elementos que lo necesitaban.

El ejemplo mencionado ahora es 
`<http://vocab.linkeddata.es/datosabiertos/recurso/cultura-ocio/agenda/Evento/1285153785025> http://schema.org/isAccesibleForFree> "false"^^xsd:boolean.`

**Comment by ocorcho** [comment]
Además, la URI debe ser /evento/ en lugar de /Evento/

**Comment by josuesalas25** [comment]
Se ha cambiado la URI de /Evento/ a /evento/.

Ahora mismo quedaría como:
`<http://vocab.linkeddata.es/datosabiertos/recurso/cultura-ocio/agenda/evento/1285153785025> <http://schema.org/isAccesibleForFree> "false"^^<http://www.w3.org/2001/XMLSchema#boolean>.`

**Comment by ocorcho** [comment]
Perfevcto.
