### ISSUE TITLE
Mover el skos al repositorio listas-codigos-skos

### ISSUE THREAD

**Issue by ocorcho** [josuesalas25/cultura-ocio-agenda-eventos-actividades#6]
Y dejar una referencia a dicho repositorio y el folder correspondiente en el directorio skos.
Debe ir en el directorio correspondiente allí y se debe añadir su URL del ConceptScheme en el README de allí

**Comment by josuesalas25** [comment]
Ya lo he añadido en el repositorio listas-codigos-skos y he hecho el pull request.
https://github.com/opencitydata/listas-codigos-skos/pull/32/commits/6925cc6c6aafec97832e0ded635f9613bd4c045f
