### ISSUE TITLE
Error en la URI del concepto Equipamiento

### ISSUE THREAD

**Issue by ocorcho** [josuesalas25/cultura-ocio-agenda-eventos-actividades#9]
En https://github.com/josuesalas25/cultura-ocio-agenda-eventos-actividades/blob/f6a4373b2712db91655a80e3e8b755333a856f59/v1.1-rc/examples/output.nt#L6

Debería ser http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras#Equipamiento
en lugar de http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/equipamiento

**Comment by josuesalas25** [comment]
Se ha realizado el cambio.

Ahora mismo el ejemplo mencionado pasa a ser <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/equipamiento-municipal/equipamiento/1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras#Equipamiento>.

**Comment by ocorcho** [comment]
Pasa lo mismo con http://vocab.linkeddata.es/datosabiertos/recurso/cultura-ocio/agenda/evento>

Mira todos los casos de conceptos y propiedades usados, para que esté bien.

**Comment by josuesalas25** [comment]
Respecto a schema:address deberia ser <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/equipamiento-municipal/equipamiento/> <http://schema.org/address> <http://vocab.linkeddata.es/datosabiertos/recurso/cultura-ocio/agenda/evento/3421/address>. o deberia ser <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/equipamiento-municipal/equipamiento/1285134251775> <http://schema.org/address> <https://schema.org/address/1285137762140>.

La diferencia está entre usar <http://vocab.linkeddata.es/datosabiertos/recurso/cultura-ocio/agenda/evento/3421/address> o  <https://schema.org/address/1285137762140>.

**Comment by josuesalas25** [comment]
https://github.com/josuesalas25/cultura-ocio-agenda-eventos-actividades/blob/b1dfc6616ee9dfe4481740e3bccb87b35a2af546/v1.1-rc/examples/output.nt#L1335

Finalmente he optado por http://vocab.linkeddata.es/datosabiertos/recurso/cultura-ocio/agenda/evento/XXX/address

**Comment by ocorcho** [comment]
Ok. Realmente no tenía sentido lo de schema.org.
